app:
  ai:
    provider: google # or OpenAI
spring:
  application:
    name: first-ai-project
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7
    openai:
      api-key: dummy
      base-url: http://localhost:12434/engines/llama.cpp
      chat:
        options:
          model: gemma3
#    openai:
#      api-key: dummy
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: mistral:7b
#    openai:
#      api-key: ${HUGGINGFACE_API_KEY} # ${GEMINI_API_KEY}
#      base-url: https://router.huggingface.co
#      chat:
#        options:
#          model: Qwen/Qwen2.5-Coder-7B-Instruct:nscale # deepseek-ai/DeepSeek-R1:fastest# gpt-4.1-mini
#          temperature: 0.7
#          max-tokens: 1000
    vertex:
      ai:
        gemini:
          project-id: product-id
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash
    huggingface:
      chat:
        api-key: ${HUGGINGFACE_API_KEY}
        url: https://router.huggingface.co
        options:
          model: Qwen/Qwen2.5-Coder-7B-Instruct:nscale # Qwen3-Coder-30B-A3B-Instruct # facebook/bart-large-cnn
          max-new-token: 1024
          temperature: 0.7
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral:7b
#          max-new-tokens: 512
#          temperature: 0.7


logging:
  level:
    root: INFO
    com:
      jialli:
        first_ai_project: INFO
    org.springframework.ai: INFO
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG #OFF
server:
  port: 8081